services:
  postgres-grs:
    image: 'postgres:17.0-alpine'
    container_name: postgres-grs
    environment:
      - 'POSTGRES_DB=grs'
      - 'POSTGRES_USER=grsuser'
      - 'POSTGRES_PASSWORD=grssecret'
    ports:
      - '5432:5432'
    networks:
      grs_network:


networks:
  grs_network:
    driver: bridge
    name: grs
