/*
 * Copyright (c) 2025, Nirav Pistolwala
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.ncraft.grs.service;

import lombok.extern.slf4j.Slf4j;

import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.MessageDigest;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.util.Arrays;
import java.util.Base64;
import java.util.HexFormat;

@Slf4j
public class RsaKemHybridCipher {

    public static final int RSA_BITS = 1024; // Switch between 1024 and 2048

    // Calculates the required buffer size (e.g., 2048 / 8 = 256 bytes)
    public static final int FIDO_RSA_BYTES = RSA_BITS / 8;

    private RsaKemHybridCipher() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }

    /**
     * Decapsulates a modern RSA-KEM payload to recover a shared AES key.
     * <p>
     * This method performs RSA decryption using the provided
     * public key to extract a raw random seed. It dynamically adjusts for Java's
     * leading-zero {@code BigInteger} quirk to perfectly reconstruct the original seed
     * generated by the authenticator. Finally, it passes the restored seed through a
     * SHA-256 Key Derivation Function (KDF) to output a 32-byte AES key.
     * </p>
     * <p>
     * <b>Security Note:</b> Intermediate key material (the plaintext seed) is
     * securely wiped from memory in a {@code finally} block immediately after derivation.
     * </p>
     *
     * @param rsaCiphertext    the raw, unpadded RSA ciphertext received from the device.
     * @param publicKey        the RSA public key used to decrypt (verify) the payload.
     * @param expectedRsaBytes the exact byte length of the RSA modulus (e.g., 128 for RSA-1024).
     * @return a strictly 32-byte array representing the derived AES symmetric key.
     * @throws IllegalArgumentException if the inputs are null, or if the ciphertext
     *                                  length does not exactly match the expected modulus size.
     * @throws GeneralSecurityException if the underlying cryptographic engine fails
     *                                  (e.g., invalid key format or algorithm unavailability).
     */
    public static byte[] extractAesKey(byte[] rsaCiphertext, PublicKey publicKey, int expectedRsaBytes) throws GeneralSecurityException {

        if (rsaCiphertext == null || publicKey == null) {
            throw new IllegalArgumentException("Ciphertext and Public Key cannot be null.");
        }

        if (rsaCiphertext.length != expectedRsaBytes) {
            throw new IllegalArgumentException("Fatal Error: Configured for RSA-" + (expectedRsaBytes * 8) +
                    " but received " + rsaCiphertext.length + " bytes!");
        }

        byte[] rawDecryptedBlock = null;
        byte[] seedZ = null;

        try {
            // Raw RSA Math: Decrypt the ciphertext using the Public Key
            Cipher cipher = Cipher.getInstance("RSA/ECB/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, publicKey);

            rawDecryptedBlock = cipher.doFinal(rsaCiphertext);

            // Fix Java's missing leading zero quirk dynamically
            seedZ = new byte[expectedRsaBytes];
            if (rawDecryptedBlock.length < expectedRsaBytes) {
                int difference = expectedRsaBytes - rawDecryptedBlock.length;
                System.arraycopy(rawDecryptedBlock, 0, seedZ, difference, rawDecryptedBlock.length);
            } else {
                System.arraycopy(rawDecryptedBlock, 0, seedZ, 0, expectedRsaBytes);
            }

            // ========================================================================
            // KEM STEP: Derive the AES key using the SHA-256
            // ========================================================================
            MessageDigest kdfBlender = MessageDigest.getInstance("SHA-256");

            return kdfBlender.digest(seedZ);

        } finally {
            if (seedZ != null) {
                Arrays.fill(seedZ, (byte) 0x00);
            }
            if (rawDecryptedBlock != null) {
                Arrays.fill(rawDecryptedBlock, (byte) 0x00);
            }
        }
    }

    /**
     * Decrypts a payload encrypted with AES in Counter (CTR) mode without padding.
     * <p>
     * This method expects the {@code encryptedPayload} to contain a 16-byte Initialization
     * Vector (IV) or Nonce at the very beginning, immediately followed by the actual ciphertext.
     * After decryption, the resulting plaintext is logged and returned as a Base64Url encoded string.
     * </p>
     *
     * @param sharedAesKey     the symmetric AES key used for decryption.
     * @param encryptedPayload a byte array containing the 16-byte nonce followed by the ciphertext.
     * @return a Base64Url encoded string representation of the decrypted plaintext data.
     * @throws IllegalArgumentException if the {@code encryptedPayload} is 16 bytes or shorter,
     *                                  meaning it cannot contain both a nonce and ciphertext data.
     * @throws GeneralSecurityException if an error occurs during the cryptographic operations
     *                                  (e.g., invalid key size, unsupported algorithm).
     */
    public static String decryptAesCtrPayload(byte[] sharedAesKey, byte[] encryptedPayload) throws GeneralSecurityException {
        if (encryptedPayload.length <= 16) {
            throw new IllegalArgumentException("Payload is too short to contain a Nonce and data!");
        }

        byte[] nonce = Arrays.copyOfRange(encryptedPayload, 0, 16);
        byte[] cipherText = Arrays.copyOfRange(encryptedPayload, 16, encryptedPayload.length);

        SecretKeySpec keySpec = new SecretKeySpec(sharedAesKey, "AES");
        IvParameterSpec ivSpec = new IvParameterSpec(nonce);

        Cipher cipher = Cipher.getInstance("AES/CTR/NoPadding");
        cipher.init(Cipher.DECRYPT_MODE, keySpec, ivSpec);

        byte[] decryptedBytes = cipher.doFinal(cipherText);

        log.debug("\n======================================");
        log.debug("DECRYPTED MESSAGE (Raw Hex): " + HexFormat.of().withUpperCase().formatHex(decryptedBytes));
        log.debug("DECRYPTED MESSAGE (Base64Url): " + byteArrayToBase64Url(decryptedBytes));
        log.debug("======================================\n");

        return byteArrayToBase64Url(decryptedBytes);
    }

    /**
     * Decodes a Base64Url encoded string into its original byte array.
     * <p>
     * This method uses the URL and Filename safe Base64 decoding scheme (recognizing
     * '-' and '_'). It is completely null-safe and automatically trims trailing or
     * leading whitespace. If the input is null or empty, it gracefully returns an
     * empty byte array rather than throwing a {@code NullPointerException}.
     * </p>
     * <p>
     * <b>Note:</b> This method expects URL-safe Base64 input. If you need to decode
     * standard Base64 strings (which use '+' and '/'), use the standard Base64
     * decoder instead to prevent {@code IllegalArgumentException}s.
     * </p>
     *
     * @param s the Base64Url encoded string to be decoded.
     * @return a byte array containing the decoded data. Returns an empty array
     * if the input string is {@code null} or empty.
     * @throws IllegalArgumentException if the provided string is not a valid
     *                                  Base64Url scheme (e.g., contains illegal characters like '+' or '/').
     */
    public static byte[] base64UrlToByteArray(String s) {
        if (s == null || s.isEmpty()) return new byte[0];
        return Base64.getUrlDecoder().decode(s.trim());
    }


    /**
     * Decodes a standard Base64 encoded string into its original byte array.
     * <p>
     * This method is null-safe and automatically trims leading or trailing whitespace.
     * If the input is null, empty, or contains only whitespace, it safely returns
     * an empty byte array rather than throwing a {@code NullPointerException}.
     * </p>
     * <p>
     * <b>Note:</b> This method uses the standard Base64 decoding scheme (recognizing
     * '+' and '/'). If you are attempting to decode a URL-safe Base64 string
     * (which uses '-' and '_'), this method will throw an exception. For URL-safe
     * decoding, use {@code Base64.getUrlDecoder()} instead.
     * </p>
     *
     * @param s the standard Base64 encoded string to be decoded.
     * @return a byte array containing the decoded data. Returns an empty array
     * if the input string is {@code null} or entirely whitespace.
     * @throws IllegalArgumentException if the provided string is not a valid
     *                                  standard Base64 scheme (e.g., contains illegal characters).
     */
    public static byte[] base64ToByteArray(String s) {
        if (s == null || s.trim().isEmpty()) {
            return new byte[0];
        }

        return Base64.getDecoder().decode(s.trim());
    }

    /**
     * Encodes a byte array into a Base64Url formatted string without padding.
     * <p>
     * This method uses the URL and Filename safe Base64 alphabet (replacing '+' with '-'
     * and '/' with '_'). It also explicitly strips the trailing '=' padding characters,
     * making the resulting string fully compliant with modern web cryptographic standards
     * (such as JWTs and FIDO2 assertions) which require unpadded URL-safe strings.
     * </p>
     *
     * @param rawBytes the raw byte array to be encoded.
     * @return the unpadded Base64Url encoded string. Returns an empty string {@code ""}
     * if the input array is {@code null} or empty.
     */
    public static String byteArrayToBase64Url(byte[] rawBytes) {
        if (rawBytes == null || rawBytes.length == 0) {
            return "";
        }

        return Base64.getUrlEncoder().withoutPadding().encodeToString(rawBytes);
    }

    /**
     * Reconstructs an RSA Public Key object from its X.509 DER-encoded byte array.
     * <p>
     * This method expects the byte array to be strictly formatted according to the
     * X.509 SubjectPublicKeyInfo standard. It is designed to process the exact
     * ~300-byte public key payload exported by the hardware authenticator.
     * </p>
     *
     * @param keyBytes the X.509 DER-encoded byte array representing the RSA public key.
     * @return the reconstructed RSA {@link PublicKey} object, ready for cryptographic operations.
     * @throws IllegalArgumentException if the provided byte array is null or empty.
     * @throws GeneralSecurityException if the RSA algorithm is unavailable in the environment,
     *                                  or if the provided bytes do not form a valid X.509 RSA public key.
     */
    public static PublicKey buildPublicKeyFromBytes(byte[] keyBytes) throws GeneralSecurityException {

        if (keyBytes == null || keyBytes.length == 0) {
            throw new IllegalArgumentException("Key bytes cannot be null or empty.");
        }

        X509EncodedKeySpec spec = new X509EncodedKeySpec(keyBytes);
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");

        return keyFactory.generatePublic(spec);
    }

}